server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes inconnues renvoient index.html
    # Nécessaire pour le routing React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
