name: CI/CD

on:
    push:
        branches: [dev, 'feature/**', main]
    pull_request:
        branches: [main, dev]

jobs:
    lint-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Cloner le dépot
              uses: actions/checkout@v4
            - name: Installer Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - run: cd Frontend && npm ci
            - run: cd Frontend && npm run lint

    lint-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - run: cd Backend && npm ci
            - run: cd Backend && npm run lint

    test-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - run: cd Backend && npm ci
            - run: cd Backend && npm test

    # ----  BUILD AND PUSH GHCR
    build-and-push-staging:
      runs-on: ubuntu-latest
      needs: [lint-frontend, lint-backend, test-backend]
      if: github.ref == 'refs/heads/dev'
      steps:
          - name: Cloner le dépôt
            uses: actions/checkout@v4

          - name: Connexion à GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build et push Backend staging
            uses: docker/build-push-action@v5
            with:
                context: ./Backend
                push: true
                tags: ghcr.io/yannou64/homecyclhome-backend:staging

          - name: Build et push Frontend staging
            uses: docker/build-push-action@v5
            with:
                context: ./Frontend
                push: true
                tags: ghcr.io/yannou64/homecyclhome-frontend:staging

    build-and-push-prod:
      runs-on: ubuntu-latest
      needs: [lint-frontend, lint-backend, test-backend]
      if: github.ref == 'refs/heads/main'
      steps:
          - name: Cloner le dépôt
            uses: actions/checkout@v4

          - name: Connexion à GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build et push Backend prod
            uses: docker/build-push-action@v5
            with:
                context: ./Backend
                push: true
                tags: ghcr.io/yannou64/homecyclhome-backend:prod

          - name: Build et push Frontend prod
            uses: docker/build-push-action@v5
            with:
                context: ./Frontend
                push: true
                tags: ghcr.io/yannou64/homecyclhome-frontend:prod

    # ---- DÉPLOIEMENT STAGING ----
    deploy-staging:
        runs-on: ubuntu-latest
        # Lance uniquement si la CI est passée et qu'on est sur dev
        needs: [build-and-push-staging]
        if: github.ref == 'refs/heads/dev'
        steps:
            - name: Copier les fichiers de config
              uses: appleboy/scp-action@v1
              with: 
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  source: "docker-compose.staging.yml,nginx/staging.conf"
                  target: "/app/homecyclhome"
            - name: Déploiement sur le VPS staging
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  script: |
                      cd /app/homecyclhome
                      echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u yannou64 --password-stdin
                      docker compose --env-file .env.staging -f docker-compose.staging.yml pull
                      docker compose --env-file .env.staging -f docker-compose.staging.yml up -d 

    # ---- DÉPLOIEMENT PROD ----
    deploy-prod:
        runs-on: ubuntu-latest
        # Lance uniquement si la CI est passée et qu'on est sur main
        needs: [build-and-push-prod]
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Copier les fichiers de config
              uses: appleboy/scp-action@v1
              with: 
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  source: "docker-compose.prod.yml,nginx/prod.conf"
                  target: "/app/homecyclhome-prod"
            - name: Déploiement sur le VPS prod
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: ${{ secrets.VPS_PORT }}
                  script: |
                      cd /app/homecyclhome-prod
                      echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u yannou64 --password-stdin
                      docker compose --env-file .env.prod -f docker-compose.prod.yml pull
                      docker compose --env-file .env.prod -f docker-compose.prod.yml up -d
